### ISSUE TITLE
No table-entry if acf_field is field type checkbox (Multiple Values)

### ISSUE THREAD

**Issue by matthiashonert** [tameroski/Post-Type-Exporter#1]
First, I found your Plugin via Google. I would like to use this on a website where people can apply via form for a puplic district committee. After the apply process we need the data via xls.

Your Plugin works like a charm with cpt and acf fields. But if acf_field is [field type checkbox](https://www.advancedcustomfields.com/resources/checkbox/) and has multiple selected values (labels), nothing will come out of it in the export-file there in the column with this field type.

Do you know how to integrate that?

**Comment by tameroski** [comment]
Hi
I made a quick fix for that. Your tests are welcome ;)

**Comment by matthiashonert** [comment]
Wow! super nice. It works.
